apiVersion: v1
kind: Service
metadata:
  labels:
    app: tigergraph
  name: tg-rest-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: tigergraph
  ports:
  - port: 9000
    name: rest
    targetPort: 9000
